server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/alumni_demo}
      auto-index-creation: true

app:
  jwt:
    issuer: "90s-alumni-demo"
    access_token_minutes: 15
    refresh_token_days: 30
    # IMPORTANT: change this in real deployment
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_64_CHARS__________________________"

logging:
  level:
    org.springframework.security: INFO
